{% set name = 'psana' %}
{% set version = '4.0.9' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-conda-{{ version }}.tar.gz
  sha256: 74dd182cab563b7674ab5357bac7a536b145565d751523c5c2078c3ff176c0da
  patches:
    - ndarray_ext.patch

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxext') }}
    - make=4.3
    - patch=2.7.6
  host:
    - python=2.7.15
    - scons=3.1.2
    - boost-cpp=1.72.0
    - boost=1.72.0
    - cython=0.29.15
    - xorg-libxfixes=5.0.3
    - qt=5.12.5
    - matplotlib-base=2.2.5
    - openmpi=4.0.5
    - ndarray-psana=1.1.8
    - hdf5=1.10.5
    - curl=7.71.1
    - libcurl=7.71.1
    - libtiff=4.1.0
    - libpng=1.6.37
    - libuuid=2.32.1
    - six=1.15.0
    - zlib=1.2.11
  run:
    - python=2.7.15
    - qt=5.12.5
    - numpy=1.16.5
    - matplotlib-base=2.2.5
    - scipy=1.2.0
    - pyzmq=19.0.0
    - hdf5=1.10.5
    - h5py=2.10.0
    - _openmp_mutex=4.5
    - mpi4py=3.0.3
    - ndarray-psana=1.1.8
    - pytables=3.5.2
    - six=1.15.0
    - curl=7.71.1
    - libcurl=7.71.1
    - libtiff=4.1.0
    - libpng=1.6.37
    - libuuid=2.32.1
    - zlib=1.2.11
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('boost-cpp') }}

test:
  commands:
    - psana -h

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis softweare for the Linac Coherent Light Source'
  description: |
    psana is software that can be used to analyze LCLS data. Using
    relatively simple python code, it is possible to analyze LCLS data
    in parallel on hundreds of CPU cores, both offline and in real-time
    while data is being taken.
  doc_url: https://confluence.slac.stanford.edu/display/PSDM/LCLS+Data+Analysis
  dev_url: https://github.com/slaclab/anarel-manage  #Is this correct?

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
